apiVersion: v1
kind: Service
metadata:
  name: nginx-official-service
spec:
  type: NodePort   ## if you use AWS or GCP you can define the load balancer, but I use Minikube
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31303
  selector:
    app: nginx-official